// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Identification: typeof import('./src/components/Identification.vue')['default']
    ManifestCode: typeof import('./src/components/ManifestCode.vue')['default']
    MoreAttributes: typeof import('./src/components/MoreAttributes.vue')['default']
  }
}

export { }
